name: smile_id
description: The Official Smile ID Flutter SDK
version: 11.0.1
homepage: "https://usesmileid.com"
repository: https://github.com/smileidentity/flutter
issue_tracker: https://github.com/smileidentity/flutter/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.3 <4.0.0"
  mockito: ^5.4.2
  pigeon: ">=17.0.0 <=22.7.2"

flutter:
  plugin:
    platforms:
      android:
        package: com.smileidentity.flutter
        pluginClass: SmileIDPlugin
      ios:
        pluginClass: SmileIDPlugin
