name: smile_id
description: The Official Smile ID Flutter SDK
version: 11.2.2
homepage: "https://usesmileid.com"

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  pigeon: ^26.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.smileidentity.flutter
        pluginClass: SmileIDPlugin
      ios:
        pluginClass: SmileIDPlugin
