name: sample
description: Smile ID Flutter Sample App
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  smile_id:
    # When depending on this package from a real application you should use:
    #   smile_id: ^x.y.z
    # The sample app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
